<?php get_header(); ?>
<div id="content">
	<?php if ( have_posts() ) while ( have_posts() ) : the_post(); ?>
		<div id="post-<?php the_ID(); ?>" <?php post_class(array('single_post', 'normal_post')); ?>>
			<div class="post-inners">

				<div class="post-title">
					<p class="supertitle"><?php the_title(); ?></p>
					<p>by <?php the_author_posts_link() ?> | <?php the_time('m-d-Y'); ?></p>
					<a href="<?php the_permalink() ?>" title="<?php the_title(); ?>"><img src="<?php echo get_template_directory_uri(); ?>/images/go.png" alt="post-arrow" /></a>  <!-- arrow for navigation -->
				</div>

				<div class="post-content">
					<?php 
						if ( has_post_thumbnail() ) { 
							echo '<!-- loades the post\'s featured thumbnail, requires Wordpress 3.0+ -->';
							echo '<div class="featured-thumbnail">'; 
							the_post_thumbnail('thumbnail'); 
							echo '</div>'; 
						}
						the_content();
					?>
					<div class="clear"></div>
					<div class="pagination">
						<?php wp_link_pages('before=<div class="pagination">&after=</div>'); ?>
					</div><!--.pagination-->
				</div><!--#post-content-->
			
				
			<div id="post-meta">
				<p id="np_date">
					Posted on <?php the_time('F j, Y'); ?> at <?php the_time() ?>
				</p>
				<!--<p>
					<?php //comments_popup_link('No comments', 'One comment', '% comments', 'comments-link', 'Comments are closed'); ?> 
				</p>-->
				<div id="np_cat_tag">
					<p class="np_big">Categories:</p> <?php the_category(', ') ?>
					<br />
					<?php the_tags('<p class="np_big">Tags: </p>', ', ', ' '); ?>
				</div>
				<div id="more_meta">
					<a href="<?php bloginfo('rss2_url'); ?>" rel="nofollow"><img class="rss" src="<?php echo get_template_directory_uri(); ?>/images/rss.png" alt="Blog RSS Feed"/></a>
					<?php post_comments_feed_link('<img class="rss" src="' . get_template_directory_uri() . '/images/rss_comment.png" alt="Comments RSS Feed"/>'); ?>
					<p id="author_link">View all posts by: <?php the_author_posts_link() ?></p> <!-- links to pages generated by author.php -->

				</div>
				<div id="post-author">
				<!-- This avatar is the user's gravatar (http://gravatar.com) based on their administrative email address -->
				<p class="gravatar"><?php if(function_exists('get_avatar')) { echo get_avatar( get_the_author_meta('email'), '80' ); } ?></p>
				<div id="authorDescription">
					<h4>Written by <?php the_author_posts_link() ?></h4>
				</div><!--#author-description -->
				</div><!--#post-author-->
			</div><!--#post-meta-->
			<div class="clear meta_bottom"></div>

			
			<!-- If a user fills out their bio info, it's included here -->
			
			</div><!--.post-inners-->

		</div><!-- #post-## -->

		<nav class="oldernewer" id="single_on">
			
			<?php 
			
			if(!get_adjacent_post(false, '', false))
				previous_post_link('%link', '<div class="older big"><p>&laquo; Older Post</p></div><!--.older-->');
			else previous_post_link('%link', '<div class="older"><p>&laquo; Older Post</p></div><!--.older-->');
			
			if(!get_adjacent_post(false, '', true))
				next_post_link('%link', '<div class="newer big"><p>Newer Post &raquo;</p></div><!--.older-->');
			else next_post_link('%link', '<div class="newer"><p>Newer Post &raquo;</p></div><!--.older-->');
			
			?>
			
		</nav><!--.oldernewer-->

		<?php comments_template( '', true ); ?>

	<?php endwhile; ?><!--end loop-->
</div><!--#content-->
<?php //get_sidebar(); ?>
<?php get_footer(); ?>